name: postgresql-9.6-build
on: [push]

jobs:
  build:
    name: postgresql-9.6-build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the environment
        run: |
          sudo mkdir -p /etc/postgresql-common/createcluster.d
          sudo touch /etc/postgresql-common/createcluster.d/pg_drop_events.conf
          sudo chmod 766 /etc/postgresql-common/createcluster.d/pg_drop_events.conf
          sudo echo 'create_main_cluster = false' > /etc/postgresql-common/createcluster.d/pg_drop_events.conf
          sudo echo "initdb_options = '-k'" >> /etc/postgresql-common/createcluster.d/pg_drop_events.conf

      - name: Install PostgreSQL 9.6
        run: |
          sudo apt-get update
          sudo apt -y install gnupg2
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
          sudo apt update
          sudo apt -y install postgresql-9.6 postgresql-common

      - name: Initialize and start postgresql cluster
        run: |
          sudo pg_createcluster 9.6 pg_drop_events -p 5432
          sudo pg_ctlcluster 9.6 pg_drop_events start

      - name: Clone pg_drop_events repository
        uses: actions/checkout@v2

      - name: Build pg_drop_events
        run: |
          sudo make clean && sudo make install

      - name: Start pg_drop_events tests
        run: |
          sudo chown postgres:postgres -R $(pwd)
          sudo -u postgres make installcheck

      - name: Report on pg_drop_events test failure
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: Regressions diff
          path: |
            regression.diffs
          retention-days: 1
